### ISSUE TITLE
Issue with mkdir_p of all added directories

### ISSUE THREAD

**Issue by eric** [travis-ci/casher#1]
I have some rake tasks that assume that if a directory doesn't exist, I should install a package in it.

Because cacher creates an empty directory, it assumes the work is done and doesn't install.

I wonder if it would make sense to have cacher not do the `mkdir_p` for an added directory, and just deal with the possibility the directory doesn't exist in `changed?` and `tar()`.

**Comment by BanzaiMan** [comment]
Is this still relevant?

We now use `md5deep` to detect file changes, and empty directories are mostly meaningless, since they are not included in the checks.

**Comment by BanzaiMan** [comment]
Replicated as https://github.com/travis-ci/travis-ci/issues/4391.
