### ISSUE TITLE
s3 download can be slow

### ISSUE THREAD

**Issue by davedash** [travis-ci/casher#3]
It might be worth experimenting with parallelism for s3 downloads.

Sometimes s3 downloads can be slow.

You could potentially speed up downloads by using "range" in curl:

```
curl --range X-Y -o part.1
```
and reassembling them.

Although it depends on the cache size too.

**Comment by BanzaiMan** [comment]
Replicated as https://github.com/travis-ci/travis-ci/issues/4392.
