### ISSUE TITLE
c/c++ workers share a cache when environment variables are used to build the matrix

### ISSUE THREAD

**Issue by theuni** [travis-ci/casher#6]
As discussed on IRC with @joshk

I believe this is actually a problem in core and not here, but logging a ticket here for discussion.

For c/c++, it seems that the compiler is the only differentiating factor when creating the slug.

Take this example:
```
language: c
cache:
  directories:
  - mydir
env:
  - FOO=foo BAR=bar
  - FOO=bar BAR=foo
```
The default compiler will be gcc.
For both builds, the slug will be: cache--compiler-gcc

This means that the builds will stomp each-other's caches. In order to prevent this, the slug would need to be appended with some unique id for each builder. The most reasonable approaches I can come up with would be:
- A hash of the env
- A user-specified unique identifier

As an incredibly hackish work-around, I've used a phony compiler (one that can run "compiler --version" without failing) here: https://travis-ci.org/coryfields/bitcoin/builds/33134451

The "true X" compilers will each result in different slugs, so they get independent caches:
```
On branch master:
cache--compiler-true1  last modified: 2014-08-20 23:03:03  size: 27.95 MiB
cache--compiler-true2  last modified: 2014-08-20 23:00:08  size: 23.57 MiB
```

It would be nice to be able to do something like this:
```
matrix:
  include:
    - cache-id: foobuild
      env: FOO=foo BAR=bar
    - cache-id: barbuild
      env: FOO=bar BAR=foo
```

**Comment by BanzaiMan** [comment]
Replicated as https://github.com/travis-ci/travis-ci/issues/4393.

I'm closing this, and disabling "issues" on this repository afterwards, so that we can track the issues in the central spot.
