### ISSUE TITLE
Adding multiple directories extract whole tar several times

### ISSUE THREAD

**Issue by vvondra** [travis-ci/casher#8]
If multiple directories are configured in .travis.yml, only one tar is produced, but when extracting the cache archive in the build with `casher add`, the whole tar is extracted again and again for each directory. Since all the listed directories are in one tar, it essentially extracts all the directories the number of times as how many there are directories.

The issue was introduced in 2317e876249f8547a7cd1800dfe2d25c67acf64e

Unfortunately, we have a pretty big tar and extracting it takes a long time.

Notice how for all entries, the time is almost the same, this is because the same thing is done 7 times.

```
53.23s adding /home/travis/build/.../vendor to cache
54.53s adding /home/travis/.npm to cache
58.03s adding /home/travis/.nvm to cache
54.92s adding /home/travis/.composer to cache
54.37s adding /home/travis/build/.../Resources/public/node_modules to cache
61.82s adding /home/travis/build/.../Resources/public/bower_components to cache
```

**Comment by apepper** [comment]
I noticed the same thing.

We are now using the following workaround: Cache only one "superfolder" e.g. `$HOME/cache` and put all folders, that needs caching as a subfolder into this "superfolder". E.g. `$HOME/cache/bundle` and `$HOME/cache/perl` etc.

**Comment by BanzaiMan** [comment]
This issue has been fixed to a degree. The directories in `cache.directories` are now passed to `casher` in chunks of 100 directories and `casher` reads the archive only one per invocation.

This is not the case with special directives such as `cache: bundler` or the equivalent `cache.bundler: true`, as these are processed separately.

I'm closing this now.
