### ISSUE TITLE
Error on mtime for a dead symlink

### ISSUE THREAD

**Issue by drogus** [travis-ci/casher#9]
When checking for changes in cache, we do an `mtime` check for all of the files found with `Dir.glob`. If one of these files is a symlink that links to a non existing file, mtime throws an error. Instead of checking for mtime of the symlinked file, we should probably check for a symlink itself with `File.lstat(file_name).mtime`

/cc @rkh

**Comment by BanzaiMan** [comment]
The file changes are now detected by md5 checksums.
